#!/bin/bash
#SBATCH --ntasks=1                    # Run on a single CPU
#SBATCH --time=00:05:00               # Time limit hrs:min:sec
#SBATCH --partition=secondary
#SBATCH --job-name="myjob"
#SBATCH --output=myjob.o%j

module load anaconda/3
module load cuda
source activate /scratch/yerong/sha

pwd; hostname; date


echo "Running plot script on a single CPU core"
srun ‑‑gres=gpu:V100 bash scripts/train_kairos.sh | tee /home/yerong2/yerong.log